let recordings=[];try{const rr=await fetch('./replay.json',{cache:'no-store'});if(!rr.ok)throw new Error('replay.json HTTP '+rr.status);recordings=await rr.json();}catch(e){const b=document.getElementById('start');if(b){b.textContent='LOAD ERROR: '+e.message;}console.error(e);}
async function replay(state){
 const ids=state.objects.map(o=>o.id).sort().join(',');
 const row=recordings.find(r=>r.state.objects.map(o=>o.id).sort().join(',')===ids);
 if(!row)throw new Error('No recorded decision for this scene. Reset to replay.');
 return {ok:true,json:async()=>({...row,calls:recordings.indexOf(row)+1,total_cost:0})};
}
import * as T from './assets/three.module.js';
import {GLTFLoader} from './assets/GLTFLoader.js';
const $=id=>document.getElementById(id),scene=new T.Scene();
scene.fog=new T.FogExp2(0x0c1520,.16);
const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;$('viewport').appendChild(renderer.domElement);
const camera=new T.PerspectiveCamera(38,1,.01,30);camera.up.set(0,0,1);camera.position.set(1.75,-2.6,2.8);camera.lookAt(.0,.1,.05);
scene.add(new T.HemisphereLight(0xcbeaf4,0x263748,2.1));
const key=new T.DirectionalLight(0xffe2cf,3.2);key.position.set(-1,-2,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-2;key.shadow.camera.right=2;key.shadow.camera.top=2;key.shadow.camera.bottom=-2;key.shadow.bias=-.0004;scene.add(key);
const rim=new T.PointLight(0x55ffd2,5,4);rim.position.set(.7,1.3,1);scene.add(rim);
const mat=(color,metalness=.08,roughness=.6)=>new T.MeshStandardMaterial({color,metalness,roughness});
function mesh(g,m,parent=scene){const o=new T.Mesh(g,m);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
const floor=mesh(new T.BoxGeometry(2.9,2.5,.045),mat(0x182735));floor.position.z=-.026;
const grid=new T.GridHelper(2.8,28,0x426171,0x273d4b);grid.rotation.x=Math.PI/2;grid.position.z=.001;scene.add(grid);
const outline=new T.LineSegments(new T.EdgesGeometry(new T.BoxGeometry(2.9,2.5,.045)),new T.LineBasicMaterial({color:0x486775}));outline.position.z=-.026;scene.add(outline);
const robot=new T.Group();scene.add(robot);robot.position.set(-.65,-.65,0);robot.rotation.z=.6;
const trackGroups=[];for(const side of [-1,1]){let g=new T.Group();robot.add(g);trackGroups.push(g);for(let i=0;i<68;i++){const tread=mesh(new T.BoxGeometry(.0085,.036,.008),mat(0x26313b),g);tread.userData.s=i/68;tread.userData.side=side;}}
function tracks(phase,turn=0){trackGroups.forEach((g,k)=>g.children.forEach(o=>{const L=.5+2*Math.PI*.036,s=((o.userData.s+phase+(k?turn:-turn))%1+1)%1*L;let x,z,a;if(s<.25){x=-.125+s;z=.036;a=0}else if(s<.25+Math.PI*.036){a=Math.PI/2-(s-.25)/.036;x=.125+.036*Math.cos(a);z=.036*Math.sin(a);a-=Math.PI/2}else if(s<.5+Math.PI*.036){x=.125-(s-.25-Math.PI*.036);z=-.036;a=0}else{a=-Math.PI/2-(s-.5-Math.PI*.036)/.036;x=-.125+.036*Math.cos(a);z=.036*Math.sin(a);a-=Math.PI/2}o.position.set(x,o.userData.side*.121,z+.041);o.rotation.y=-a;}));}tracks(0);
const home={x:-.65,y:-.65};const homePad=mesh(new T.CylinderGeometry(.25,.25,.009,64),mat(0x21433f));homePad.rotation.x=Math.PI/2;homePad.position.set(home.x,home.y,.003);
const homeRing=mesh(new T.TorusGeometry(.235,.003,8,64),new T.MeshBasicMaterial({color:0x6cf8c7}));homeRing.position.set(home.x,home.y,.01);
const obstacles=[{x:.2,y:.22,r:.15}];for(const o of obstacles){let stone=mesh(new T.CylinderGeometry(o.r*.85,o.r,.16,8),mat(0x3d5362));stone.rotation.x=Math.PI/2;stone.position.set(o.x,o.y,.08);let stem=mesh(new T.CylinderGeometry(.01,.015,.22,8),mat(0x5e8d80));stem.rotation.x=Math.PI/2;stem.position.set(o.x,o.y,.22);for(let i=0;i<5;i++){let leaf=mesh(new T.SphereGeometry(.055,8,6),mat(0x5ca68b));leaf.scale.set(1.8,.6,.5);leaf.position.set(o.x+Math.cos(i*1.25)*.035,o.y+Math.sin(i*1.25)*.035,.3+i*.007);leaf.rotation.z=i*1.25;}}
const defs=[['can_1','CAN 01','can',-.22,-.03],['bottle_1','BOTTLE 01','bottle',-.58,-.25],['can_2','CAN 02','can',.75,-.42],['bottle_2','BOTTLE 02','bottle',.72,.66],['paper_1','PAPER','paper',-.72,.60],['cup_1','CUP','cup',-.07,.76]];
const objects=defs.map(([id,label,kind,x,y])=>{const group=new T.Group();scene.add(group);group.position.set(x,y,0);let body;if(kind==='can'){body=mesh(new T.CylinderGeometry(.026,.026,.065,24),mat(0xffa58b,.55,.33),group);body.rotation.x=Math.PI/2;body.position.z=.033;for(const z of [.002,.064]){const cap=mesh(new T.CylinderGeometry(.0265,.0265,.004,24),mat(0xc4d1d8,.8,.25),group);cap.rotation.x=Math.PI/2;cap.position.z=z;}}else if(kind==='bottle'){body=mesh(new T.CylinderGeometry(.019,.023,.073,18),mat(0x6cafd7,.2,.28),group);body.rotation.x=Math.PI/2;body.position.z=.038;const neck=mesh(new T.CylinderGeometry(.009,.017,.02,16),mat(0x9bcede,.2,.3),group);neck.rotation.x=Math.PI/2;neck.position.z=.084;const cap=mesh(new T.CylinderGeometry(.01,.01,.009,16),mat(0xe5f0e9),group);cap.rotation.x=Math.PI/2;cap.position.z=.097;}else if(kind==='paper'){body=mesh(new T.IcosahedronGeometry(.033,1),mat(0xf0e5c7),group);body.scale.z=.55;body.position.z=.018;}else{body=mesh(new T.CylinderGeometry(.028,.018,.052,16,1,true),new T.MeshStandardMaterial({color:0xe9d1a6,side:T.DoubleSide}),group);body.rotation.x=Math.PI/2;body.position.z=.029;}
const ring=mesh(new T.TorusGeometry(.065,.002,6,40),new T.MeshBasicMaterial({color:0x567989}),scene);ring.position.set(x,y,.008);const el=document.createElement('span');el.className='label';el.textContent=label;$('labels').appendChild(el);return{id,label,kind,x,y,group,ring,el,collected:false};});
let routeLine=null;const targetBeacon=mesh(new T.CylinderGeometry(.07,.07,.25,32,1,true),new T.MeshBasicMaterial({color:0x6cf8c7,transparent:true,opacity:.06,side:T.DoubleSide,depthWrite:false}));targetBeacon.rotation.x=Math.PI/2;targetBeacon.visible=false;
const missions={cans:{title:'PICK UP<br><em>THE CANS.</em>',instruction:'Collect only cans. Leave bottles, paper and cups untouched. Return home once all reachable cans have been collected.'},bottles:{title:'NOW PICK<br><em>THE BOTTLES.</em>',instruction:'Collect only bottles. Leave cans, paper and cups untouched. Return home once all reachable bottles have been collected.'},all:{title:'LEAVE IT<br><em>CLEANER.</em>',instruction:'Collect all reachable litter, preferring the nearest object. Return home when finished.'},home:{title:'TIME TO<br><em>COME HOME.</em>',instruction:'Return home immediately without collecting any more litter.'}};
let mission='cans',running=false,busy=false,revision=0,mode='idle',selected=null,route=[],pickupTime=0,holdTime=0,phase=0,turnPhase=0,collected=0,model=null,motion=null,armNodes={},apiCount=0,pendingDecision=false;
const histories=[];function log(s){histories.unshift(s);$('history').replaceChildren(...histories.slice(0,4).map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));}function status(a,b){$('phase').textContent=a;$('action').textContent=b;}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800);}
function setMission(k){mission=k;revision++;$('mission').innerHTML=missions[k].title;document.querySelectorAll('[data-mission]').forEach(b=>b.classList.toggle('active',b.dataset.mission===k));log('Mission: '+k.toUpperCase());if(running&&mode!=='pick'){mode='idle';route=[];clearTarget();}if(mode==='pick')pendingDecision=true;}
document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>setMission(b.dataset.mission));
function setArm(matrices){for(const [k,m] of Object.entries(matrices)){const node=armNodes[k];if(node){node.matrix.fromArray(m.flat()).transpose();node.matrixAutoUpdate=false;}}}
function clearTarget(){selected=null;targetBeacon.visible=false;objects.forEach(o=>{o.el.classList.remove('target');o.ring.material.color.setHex(0x567989);});if(routeLine){scene.remove(routeLine);routeLine.geometry.dispose();routeLine=null;}}
function obstacle(x,y){return obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<o.r+.22)||Math.abs(x)>1.18||Math.abs(y)>1.02;}
function pathTo(x,y){const h=.065,key=(a,b)=>a+','+b,start=[Math.round(robot.position.x/h),Math.round(robot.position.y/h)],goal=[Math.round(x/h),Math.round(y/h)];if(obstacle(x,y))return null;let open=[start],cost=new Map([[key(...start),0]]),prev=new Map(),closed=new Set();let steps=0;
while(open.length&&steps++<4000){open.sort((a,b)=>(cost.get(key(...a))+Math.hypot(a[0]-goal[0],a[1]-goal[1]))-(cost.get(key(...b))+Math.hypot(b[0]-goal[0],b[1]-goal[1])));const c=open.shift(),ck=key(...c);if(closed.has(ck))continue;closed.add(ck);if(c[0]===goal[0]&&c[1]===goal[1]){let p=[{x,y}],k=ck;while(prev.has(k)){const v=k.split(',').map(Number);p.unshift({x:v[0]*h,y:v[1]*h});k=prev.get(k);}return p;}
for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const a=c[0]+dx,b=c[1]+dy,n=key(a,b);if(obstacle(a*h,b*h)||obstacle((c[0]+dx*.5)*h,(c[1]+dy*.5)*h))continue;const g=cost.get(ck)+Math.hypot(dx,dy);if(g<(cost.get(n)??Infinity)){cost.set(n,g);prev.set(n,ck);open.push([a,b]);}}}return null;}
function approach(o){let best=null;for(let i=0;i<12;i++){let a=i*Math.PI/6;let x=o.x-.315*Math.cos(a),y=o.y-.315*Math.sin(a);let p=pathTo(x,y);if(!p)continue;let len=0,prev=robot.position;for(const w of p){len+=Math.hypot(w.x-prev.x,w.y-prev.y);prev=w;}if(!best||len<best.len)best={path:p,len,angle:a};}return best;}
function drawRoute(p){if(routeLine){scene.remove(routeLine);routeLine.geometry.dispose();}routeLine=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(robot.position.x,robot.position.y,.014),...p.map(v=>new T.Vector3(v.x,v.y,.014))]),new T.LineDashedMaterial({color:0x6cf8c7,dashSize:.035,gapSize:.018}));routeLine.computeLineDistances();scene.add(routeLine);}
async function decide(){if(busy||!running)return;busy=true;const rev=revision;status('RECORDED JEV DECISION','Replaying a real API response from the recorded run.');$('decision').textContent='Thinking…';const options=objects.filter(o=>!o.collected).map(o=>({id:o.id,kind:o.kind,reachable:!!approach(o),distance_m:+Math.hypot(o.x-robot.position.x,o.y-robot.position.y).toFixed(2)}));const state={instruction:missions[mission].instruction,robot:'MOSS tracked litter-collection rover in simulation',battery_percent:86,bin_full:collected>=6,already_home:Math.hypot(robot.position.x-home.x,robot.position.y-home.y)<.06,objects:options};
try{const r=await replay(state);const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');apiCount++;$('latency').innerHTML=d.latency_ms.toLocaleString()+'<span> ms</span>';$('calls').textContent=d.calls+' recorded decisions';$('cost').textContent='$'+d.total_cost.toFixed(6);if(rev!==revision||!running)return;
const answer=d.answer;const labels={home:'HOME STATION',wait:'WAIT',...Object.fromEntries(objects.map(o=>[o.id,o.label]))};$('decision').textContent=labels[answer.choice]||answer.choice;
$('probabilities').replaceChildren(...Object.entries(answer.probabilities||{}).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([id,p])=>{const div=document.createElement('div');div.className='prob'+(id===answer.choice?' winner':'');const line=document.createElement('div');line.className='prob-label';const name=document.createElement('span');name.textContent=labels[id]||id;const value=document.createElement('b');value.textContent=(p*100).toFixed(1)+'%';line.append(name,value);const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('div');fill.style.width=(100*p)+'%';bar.append(fill);div.append(line,bar);return div;}));
log('Jev → '+labels[answer.choice]+' · '+d.latency_ms+' ms');clearTarget();
if(answer.choice==='wait'){running=false;status('WAITING','Jev chose to wait.');buttons();return;}
if(answer.choice==='home'){route=pathTo(home.x,home.y)||[];if(Math.hypot(robot.position.x-home.x,robot.position.y-home.y)<.07){finish();return;}mode='home';drawRoute(route);status('RETURNING HOME','Mission complete. Heading back.');return;}
selected=objects.find(o=>o.id===answer.choice&&!o.collected);const plan=selected&&approach(selected);if(!plan)throw new Error('No collision-free route to selected object. Robot stopped.');route=plan.path;selected.angle=plan.angle;selected.el.classList.add('target');selected.ring.material.color.setHex(0x6cf8c7);targetBeacon.position.set(selected.x,selected.y,.13);targetBeacon.visible=true;drawRoute(route);mode='highlight';holdTime=1.3;status('TARGET LOCKED',selected.label+' selected. Moving to collect.');toast(selected.label+' SELECTED');
}catch(e){running=false;mode='idle';status('API / PLANNING ERROR',e.message);$('decision').textContent='Paused — no fallback';log(e.message);buttons();}finally{busy=false;}}
function buttons(){$('start').hidden=running;$('pause').hidden=!running;$('start').textContent=collected?'CONTINUE →':'LET’S CLEAN →';}
function finish(){running=false;mode='idle';clearTarget();status('BACK AT BASE',collected+' pieces collected. A little cleaner.');toast('MISSION COMPLETE');log('MOSS returned home.');buttons();}
$('start').onclick=()=>{running=true;buttons();};$('pause').onclick=()=>{running=false;status('PAUSED','Ready when you are.');buttons();};
$('reset').onclick=()=>{revision++;running=false;mode='idle';clearTarget();collected=0;robot.position.set(home.x,home.y,0);robot.rotation.z=.6;objects.forEach(o=>{scene.add(o.group);o.group.position.set(o.x,o.y,0);o.group.rotation.set(0,0,0);o.collected=false;o.el.className='label';o.ring.visible=true;});if(motion)setArm(motion.travel);$('collected').textContent='0';$('decision').innerHTML='Waiting for<br>your mission.';$('probabilities').innerHTML='<div class="placeholder">New scene. Real decisions.</div>';histories.length=0;log('Scene reset.');buttons();status('READY TO ROLL','Your call. Its next move.');};
let last=performance.now(),elapsed=0;function rotateToward(a,dt){let e=Math.atan2(Math.sin(a-robot.rotation.z),Math.cos(a-robot.rotation.z));let w=T.MathUtils.clamp(e,-dt*1.9,dt*1.9);robot.rotation.z+=w;turnPhase+=w*.04;return Math.abs(e);}
function nav(dt){if(!route.length){if(mode==='home'){finish();return;}mode='align';return;}const p=route[0],dx=p.x-robot.position.x,dy=p.y-robot.position.y,d=Math.hypot(dx,dy);if(d<.027){route.shift();return;}let err=rotateToward(Math.atan2(dy,dx),dt);if(err<.17){const step=Math.min(d,.26*dt);robot.position.x+=Math.cos(robot.rotation.z)*step;robot.position.y+=Math.sin(robot.rotation.z)*step;phase+=step*1.7;}}
function step(dt){if(!running)return;if(mode==='idle'&&!busy){decide();return;}if(mode==='highlight'){holdTime-=dt;if(holdTime<=0)mode='navigate';}else if(mode==='navigate'||mode==='home')nav(dt);else if(mode==='align'){if(rotateToward(selected.angle,dt)<.015){mode='pick';pickupTime=0;status('PICK. LIFT. DROP.','Collecting '+selected.label+'.');}}else if(mode==='pick'){
pickupTime+=dt;let f=Math.min(149,Math.floor(pickupTime*22));setArm(motion.frames[f].matrices);if(f>=24&&f<99){const p=new T.Vector3(...motion.frames[f].tcp);robot.localToWorld(p);selected.group.position.copy(p);selected.group.position.z-=.025;}else if(f>=99&&!selected.collected){selected.collected=true;robot.attach(selected.group);selected.group.position.set(-.065+(collected%2)*.035,-.025+Math.floor(collected/2)*.022,.21);selected.group.rotation.set(0,0,0);selected.el.classList.add('done');selected.ring.visible=false;collected++;$('collected').textContent=collected;toast('+1 COLLECTED');log(selected.label+' → bin.');targetBeacon.visible=false;}if(f===149){mode='idle';clearTarget();pendingDecision=false;}}
}
function tick(now){requestAnimationFrame(tick);const dt=Math.min(.05,(now-last)/1000);last=now;elapsed+=dt;if(model&&motion)step(dt);tracks(phase,turnPhase);if(selected&&!selected.collected){const s=1+.1*Math.sin(elapsed*5);selected.ring.scale.setScalar(s);targetBeacon.material.opacity=.04+.03*(1+Math.sin(elapsed*4))/2;}const rect=$('viewport').getBoundingClientRect();objects.forEach(o=>{if(o.collected)return;const p=new T.Vector3(o.x,o.y,.12).project(camera);o.el.style.left=((p.x+1)*rect.width/2)+'px';o.el.style.top=((1-p.y)*rect.height/2)+'px';});renderer.render(scene,camera);}
const resize=()=>{const r=$('viewport').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe($('viewport'));resize();requestAnimationFrame(tick);
try{const [g,m,health]=await Promise.all([new Promise((res,rej)=>new GLTFLoader().load('./assets/moss.glb',res,ev=>{if(ev.total){$('start').textContent='LOADING MOSS… '+Math.round(100*ev.loaded/ev.total)+'%';}},rej)),fetch('./assets/motion.json').then(r=>r.json()),Promise.resolve({ready:true})]);model=g.scene;robot.add(model);motion=m;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}if(o.name.startsWith('arm_'))armNodes[o.name.slice(4)]=o;});setArm(motion.travel);$('connection').textContent=health.ready?'RECORDED RUN':'API KEY REQUIRED';$('start').disabled=!health.ready;buttons();log('MOSS loaded. Recorded replay ready.');}catch(e){status('LOAD ERROR',e.message);$('connection').textContent='NOT READY';$('start').textContent='LOAD FAILED';console.error(e);}

document.querySelectorAll('[data-mission]').forEach(b=>{if(b.dataset.mission!=='cans'){b.disabled=true;b.title='Other missions are available in the protected live demo';}});
